import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // 自动生成侧边栏
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  // 手动生成侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  guide: ["guide/getStarted"],
  comp: {
    XphForm: [
      "comp/form/base",
      "comp/form/properties/items/properties/component/index",
    ],
    XphTable: ["comp/table/base"],
    XphActions: ["comp/actions/base"],
    XphDialog: ["comp/dialog/base"],
    XphAuth: ["comp/auth/base"],
    XphCrudFormDialog: ["comp/crudFormDialog/base"],
  },
  extends: ["comp/extends/base"],
  api: [
    {
      type: "category",
      label: "API",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: require("./docs/api/typedoc-sidebar.cjs"),
    },
  ],
};

export default sidebars;
